market/urls.py
from django.urls import path
from .views import (
    StockListView,
    StockDetailView,
    UserStockCreateView,
    UserStockListView,
    HomeView
)

app_name = 'market'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('stocks', StockListView.as_view(), name='list_stocks'),
    path('stocks/<int:pk>/', StockDetailView.as_view(), name='detail_stock'),
    path('user/stocks/create', UserStockCreateView.as_view(), name='create_user_stock'),
    path('user/stocks', UserStockListView.as_view(), name='list_user_stocks'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('market.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path


app_name = 'user'

urlpatterns = [

]

market/models.py
from django.db import models
from model_utils.models import TimeStampedModel

from users.models import User

class Stock(TimeStampedModel):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=200, null=True)
    logo = models.CharField(max_length=500, null=True)
    sector = models.CharField(max_length=200, null=True,)

    class Meta:
        verbose_name = 'stock'
        verbose_name_plural = 'stocks'

    def __str__(self):
        return self.name

class Quote(TimeStampedModel):
    price = models.DecimalField(max_digits=5, decimal_places=2)
    stock = models.ForeignKey(
        Stock, related_name='quotes', on_delete=models.CASCADE, default=None
    )

    class Meta:
        verbose_name = 'quote'
        verbose_name_plural = 'quotes'

class UserStock(TimeStampedModel):
    user = models.ForeignKey(
        User, related_name='user', on_delete=models.CASCADE
    )
    stock = models.ForeignKey(
        Stock, related_name='stock', on_delete=models.CASCADE
    )
    max_price = models.DecimalField(max_digits=5, decimal_places=2)
    min_price = models.DecimalField(max_digits=5, decimal_places=2)

users/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ...

users/forms.py
from django.contrib.auth import forms

from .models import User

class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User

class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User

market/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic import DetailView, CreateView
from django.views import View

from .models import Stock, UserStock
from .form import UserStockCreateForm

class HomeView(View):
    template_name = "index.html"
    
    def get(self, request):
        return render(request, self.template_name)

class StockListView(ListView):
    model = Stock
    paginate_by = 30

class StockDetailView(DetailView):
    model = Stock
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class UserStockListView(ListView):
    model = UserStock
    paginate_by = 15

class UserStockCreateView(CreateView):
    model = UserStock
    stock = Stock
    form = UserStockCreateForm
    fields = ['stock', 'max_price', 'min_price']
    template_name = 'market/userstock_form.html'
    success_url = 'market:list_user_stocks'

    def get(self, request):
        context = {
            "stocks": self.stock.objects.all(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        model = UserStock()
        model.user = request.user

        form = self.form(request.POST, instance=model)

        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            return redirect("market:create_user_stock")

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="description" content="Market">
</head>

<body class="">
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'market:home' %}" class="nav-link">
            <div class="container-fluid">
                <span class="navbar-brand mb-0 h1">Inoa</span>
            </div>
        </a>

        <a href="{% url 'market:list_stocks' %}" class="nav-link">
            <div class="container-fluid">
                <span class="navbar-brand mb-0 h1">All Stocks</span>
            </div>
        </a>

        <a href="{% url 'market:list_user_stocks' %}" class="nav-link">
            <div class="container-fluid">
                <span class="navbar-brand mb-0 h1">Your Stocks</span>
            </div>
        </a>

        <a href="{% url 'market:create_user_stock' %}" class="nav-link">
            <div class="container-fluid">
                <span class="navbar-brand mb-0 h1">Follow Stock</span>
            </div>
        </a>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="description" content="Market">
</head>

<body class="">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Inoa</span>
        </div>
    </nav>

    <section class="container p-4">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5 text-center">
                <h1 class="display-5 fw-bold">Inoa</h1>
            </div>
        </div>

        <div class="row align-items-md-stretch">
            <a href="{% url 'market:list_stocks' %}" class="nav-link col-md-6">
                <div class="h-100 p-5 mb-4 text-bg-dark rounded-3 text-center">
                    <h2>All Stocks</h2>
                </div>
            </a>
            <a href="{% url 'market:list_user_stocks' %}" class="nav-link col-md-6">
                <div class="h-100 p-5 text-bg-dark border rounded-3 text-center">
                    <h2>Your Stocks</h2>
                </div>
            </a>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

templates/market/stock_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="container pt-5">   
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{object.logo}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ object.code }}</h5>
              <p class="card-text">{{ object.name }}</p>
              <p class="card-text">{{ object.sector }}</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card text-bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Price</div>
        <div class="card-body">
          <h5 class="card-title">R$ {{object.quotes.last.price}}</h5>
          <p class="card-text"><small class="text-muted">Last updated {{object.quotes.last.created}} </small></p>
        </div>
</section>


{% endblock content %}

templates/market/stock_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="container pt-5"">
    <div class="row row-cols-1 row-cols-md-5 g-4">
        {% for stock in object_list %}
        <div class="col">
            <a href="{% url 'market:detail_stock' stock.id %}" class="nav-link">
            <div class="card h-100 shadow">
                <img src="{{stock.logo}}" class="card-img-top" alt="{{ stock.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ stock.code }}</h5>
                    <p class="card-text">{{ stock.name }}</p>
                    <p class="card-text">{{ stock.sector }}</p>
                    <p class="card-text">R$ {{ stock.quotes.last.price }}</p>
                </div>
            </div>
            </a>
        </div>
        {% empty %}
        <p>No Stock</p>
        {% endfor %}
    </div>

    <div class="container p-4">
        <div class="pagination justify-content-center">
            <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">next</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
            </span>
            </div>
        </div>
      </nav>
</section>



{% endblock content %}

templates/market/userstock_form.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<form action="" class="container" method="post">
    {% csrf_token %}
    <fieldset>
        <legend> Follow a new action </legend>
        <div class="mb-3">
            <select class="form-select" name="stock" required id="stock">
                <option value="" selected>---------</option>
                {% for stock in stocks %}
                <option value="{{ stock.id }}">{{ stock.name }}</option>
                {% empty %}
                {% endfor %}
            </select><br>
        </div>

        <label for="min_price" class="form-label">Min Price</label>
        <input class="form-control" name="min_price" required id="min_price"></input><br>

        <label for="max_price" class="form-label">Max Price</label>
        <input class="form-control" name="max_price" required id="max_price"></input><br>

        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>


{% endblock content %}

templates/market/userstock_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="container pt-5">
    <div class="row row-cols-1 row-cols-md-5 g-4">
        {% for user_stock in object_list %}
        <div class="col">
            <a href="{% url 'market:detail_stock' user_stock.stock.id %}" class="nav-link">
            <div class="card h-100 shadow">
                <img src="{{user_stock.stock.logo}}" class="card-img-top" alt="{{ user_stock.stock.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ user_stock.stock.code }}</h5>
                    <p class="card-text">{{ user_stock.stock.name }}</p>
                    <p class="card-text">{{ user_stock.stock.sector }}</p>
                    <p class="card-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="green" class="bi bi-arrow-up-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z"/>
                        </svg>  R$ {{ user_stock.max_price }}<br>
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="red" class="bi bi-arrow-down-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
                        </svg>  R$ {{ user_stock.min_price }}</p>
                </div>
            </div>
            </a>
        </div>
        {% empty %}
        <p>No Stock</p>
        {% endfor %}
    </div>

</section>


{% endblock content %}